### ISSUE TITLE
re-sync release/EPIC1.0 to reflect the change from release/public-v1.0.0

### ISSUE THREAD

**Issue by jkbk2004** [NOAA-PSL/land-offline_workflow#29]
## Describe the issue. 
1. resolve code divergence issue between the two branches
2. identify and resolve the exact gap and potential issues for the future application of the code change
3. suggested approaches: re-sync up release/EPIC1.0 reverted to original (sometime Feb 5) version/commit to add in advanced code changes and features from release/public-v1.0.0

## Describe the problem and why it matters.
1. The described re-sync approach is needed due to limited timeline and resource. This will allow a path forward to continuous code update and code release through ufs community.
2. Prepare a series of PRs to merge in approved code changes 

## Test output
1. Set up baseline experiment on hera
2. Test and validate experiment results for each PR

## Will addressing this issue change the DA_IMS_test output? If not, what are the expected changes?
1. not directly applied for IMS DA test but the advancement of code base will improve the code management functionality to handle future IMS DA test and features

**Comment by jkbk2004** [comment]
@ClaraDraper-NOAA @barlage we need a review about this issue.

**Comment by ulmononian** [comment]
@rhaesung @jkbk2004  in support of this effort, please see my comments regarding testing the current land DA system (based on https://github.com/ulmononian/land-offline_workflow/tree/release/public-v1.0.0; minor modulefile changes compared to the EPIC version) with beta installations of the spack-stack unified environment on hera https://github.com/ufs-community/ufs-weather-model/issues/1651#issuecomment-1474213444 and orion https://github.com/ufs-community/ufs-weather-model/issues/1651#issuecomment-1474213444.

**Comment by yichengt90** [comment]
Thanks @ulmononian  . I also conducted ctest for land DA system using beta spack-stack on both Hera & Orion. All tests passed.
